import ReduxProvider from '@/redux/providers';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App, ConfigProvider, theme as antdTheme } from 'antd';
import 'antd/dist/reset.css';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'MAC Scholarship',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico' }, { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' }, { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' }],
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const darkMode = false;
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              algorithm: darkMode ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
              token: {},
            }}
          >
            <ReduxProvider>
              <App>{children}</App>
            </ReduxProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
